### ISSUE TITLE
Expanding terms to cover infectious structures

### ISSUE THREAD

**Issue by johnbeve** [infectious-disease-ontology-extensions/ido-core#12]
Assuming the adjustment to IDO making space for infectious structures is accepted, there are several terms that should be expanded beyond infectious agents to permit infectious structures. For example (paraphrasing from email correspondence with Shane): 

_reservoir of infectious agent role_ should perhaps be expanded to _reservoir of pathogen role_ to cover viruses (The current OWL definition is such that it inheres in some material entity and is the location of some infectious agent, which would exclude viruses from having reservoirs. 

Feel free to add terms that need to be expanded here if they've not yet been addressed in bioportal or elsewhere.

**Comment by PhiBabs935** [comment]
**One general issue to keep in mind in considering the putative changes canvassed below: in creating IDO, what was the rationale for distinguishing pathogens and infectious agents? After all, these terms are often used synonymously in the literature. But I assume IDO wants to draw an important ontological distinction between them that is perhaps not always kept in mind as carefully in the literature (hence the specificity of infectious disposition in comparison to its parent pathogenic disposition). For instance, is entry through portals of entry something that all pathogens can do, or just something that infectious agents can do? I may be overthinking it here, what do you think? My worry is just whether the proposed changes might end up eroding the distinctions between pathogen and infectious agent IDO was originally meant to capture. But this is an area where we might need to clarification from Lindsay**

Corresponding to my change to _reservoir of infectious agent role_ mentioned in the original post, 

_infectious agent reservoir_ would be changed to _pathogen reservoir_, with its textual and OWL definition changed to refer to _reservoir of pathogen role_.

_infectious agent portal of entry role_ and _infectious agent portal of exit role_
Assuming that occurrences of 'infectious agent' are changed to 'pathogen' in each of these terms (both in their labels and textual definitions), the following terms would of course have to be modified accordingly:

_infectious agent portal of entry_ and _infectious agent portal of exit_

**Comment by johnbeve** [comment]
You're right that we should keep an eye on this distinction. I've been treating pathogens as a broader class than infectious agents, since there are examples of material entities that may realize processes resulting in disorder but which are not disposed to be transmitted into hosts. For example, _clostridium botulinum_ is pathogenic if ingested, is not capable of infecting hosts. 

I'm thinking examples like that are sufficient to distinguish the parent class from its children. What do you think?

**Comment by PhiBabs935** [comment]
That sounds right to me. I also emailed Lindsay yesterday, and this seems to answer the question I had for her about the difference between pathogens and infectious agents. It has to do with the fact that not all pathogens have an infectious dispositions, such as the _clostridium botulinum_ example, as they lack some of the subdispositions of infectious disposition (as you point out, no disposition to infect a host).

I asked her for examples, and I hope she can provide some more in addition to the _clostridium botulinum_ example already mentioned in IDO (i.e. that it can bear the pathogen role but not the infectious agent roles).

This brings up a related issue that I asked Lindsay about in my email: currently we are defining _pathogen transporter role_ (your new label for _infectious agent transporter role_) as: Role borne by a material entity when an infectious agent or structure is located in or on the entity and realized in the transmission of the infectious agent or structure.

Now, it seems to me that when you ingest _clostridium botulinum_ because it is present in some food you ate, the food is playing the role of a pathogen transporter (there is a subclass called 'fomite role' that covers non-living vehicles for pathogen transmission).

But both the original definition of _infectious agent transporter role_ and the current definition of _pathogen transporter role_ would exclude the case of food being a transporter for _clostridium botulinum_ because this bacterium doesn't qualify as either an infectious agent or an infectious structure.

**Comment by johnbeve** [comment]
This is very helpful; I think you're right here, which suggests we should expand the definition of pathogen transporter role to pathogens in general, rather than restrict it to infectious agents or structures.  Does that sound right to you?

If so, I'll go ahead and add these changes to the list of things to update for the next rollout coming shortly.

**Comment by PhiBabs935** [comment]
Yes, this seems the correct move to me.

**Comment by PhiBabs935** [comment]
Some more terms that have to be edited to reflect infectious structures:

'infectious structure(s) needs to be added to the definition:
_systemic infection_ 
_local infection_
_intracellular infection_ (though the OWL definition was modified to include infectious structure)
_extracellular infection_ (OWL definition is already fixed)
_complex infection_ 

Also, I assume that the terms "acellular infectious agent birth" and "acellular infectious agent death" will be changed to 'structure' eventually (if not already?)

**Comment by PhiBabs935** [comment]
Found another term that needs curation: _herd immunity to infectious organism_. 
Label will need to be changed to accommodate infectious structures. But also the definition.

**Comment by PhiBabs935** [comment]
Also: _resistance to infectious agent_ (subclass of _protective resistance_)
As well as all of its subclasses (and their subclasses) need to be modified for infectious structures.

**Comment by johnbeve** [comment]
Got it!

**Comment by PhiBabs935** [comment]
_infectious agent reservoir_ The label and textual definition still need to to be updated. 

Besides that, it looks like you curated all the other terms I mentioned already.

**Comment by johnbeve** [comment]
Getting it done, woot!

**Comment by PhiBabs935** [comment]
hell yeah!!!
