### ISSUE TITLE
Host Role

### ISSUE THREAD

**Issue by PhiBabs935** [infectious-disease-ontology-extensions/ido-core#17]
Here I will consider how to address objections raised by Werner Ceuster, and the Apollo-SV team, to IDO _host role_

_host role_ =def Role borne by an organism in virtue of the fact that its extended organism contains a material entity other than the organism. 

Here (https://pubmed.ncbi.nlm.nih.gov/27538448/) the Apollo-SV team has objected: "Under these definitions, any organism that has an artificial joint, a penny in its gut, or an arrow through its chest is a host."

I think that this sort of worry can be addressed by putting restrictions on the sort of entities that 'material entity' ranges over in the definition.

Apollo-SV defines a host as follows: "An organism of a particular biological taxon that is the site of reproduction of an organism of a different taxon." And they note that this covers the case of infection and of colonization. 

Given that the processes of infection and colonization are both processes by which an entity is able to reproduce in another organism, I think that we should just make use of this feature in our host role definition as well. So I suggest something along the lines of:

_host role_ =def Role borne by an organism in virtue of the fact that its extended organism contains a material entity other than the organism, where the material entity makes use of that organism as a site of reproduction or a site of replication.

Just need to make sure this is sufficiently different from IDO 'symbiont host role'--it is certainly different in the sense that the latter specifies that the hosted organism is also an organism. But we may need to work on this more.

I think that something along these lines also allows us to address Werner's comments. They were the following:

1: Paraphrasing: the use of 'organism' in the definition is ambiguous. It can mean for instance a human being minus the parts that belong to its extended organism, or it could mean for instance a bacterium from the microbiome. 

John, this isn't even really an issue right? Bacteria can serve as hosts for viruses, as in the case of bacteriophages. 

2: "In light of the extended organism definition, women with tampons and men with hats are all bearing a host role"

This comment is related to another worry of Werner's that 'extended organism' is too broad because it encompasses such entities. But my suggested fix to the definition rules these out as cases in which a host role is borne for the same reason it rules out the cases brought up by the Apollo-SV people.

What do people think?

**Comment by PhiBabs935** [comment]
I should point out that Lindsay did admit (here: https://github.com/infectious-disease-ontology/infectious-disease-ontology/issues/2) that the host terms from IDO are more general than infectious diseases, but noted that they were included at the time because they were needed and IDO consistent terms didn't exist elsewhere. 

So, I suggest that we keep the host terms for now, but provide a note in the IDO paper, and a corresponding editor’s comment on the terms in the OWL file: We would note why we have them in IDO currently, but note that they will be ported out to an appropriate ontology eventually.

**Comment by johnbeve** [comment]
I think Lindsay and I are of similar thinking here. I think we need a host role term that's broad, but it shouldn't be part of IDO, we should import it from elsewhere. 

I'd introduced a sibling to 'symbiont host role' labeled 'pathogen host role' - Host role borne by an organism having a pathogen as part of its extended organism - with subclasses covering infectious agent host, structure host, symptomatic host, asymptomatic host. If we pushed the parent class 'host role' to another ontology, would we need anything other than these classes? 

I think Werner's first concern is a feature not a bug, for the reason you mention. 

As for the second, at the highest level of generality, I'm fine with saying someone wearing a hat bears a host role, but this of course should be imported from elsewhere. Of course, we're not interested in that sort of host, which is why we focus on a subclass of hosts, as I've been thinking, either symbiont hosts or pathogen hosts. 

If this sounds right, I'll make a note in the definition of host role to avoid confusion.

**Comment by PhiBabs935** [comment]
Hey John. This sounds right to me at first glance, but will need to think more about it today. As I am clarifying in the paper, there is no way to exclude things like hats and swallowed marbles from the extended organism, but for the purposes of using this class in our representation of pathogenesis and host-pathogen interactions, it doesn't really matter given that the relevant representation in IDO make use of 'establishment of localization in host' (and thus GO localization).

**Comment by johnbeve** [comment]
Ah yes, perfect. Thanks!
